//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsAppEli.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int id_user { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string patronymic_name { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> pin_code { get; set; }
    
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
